export const PRIORITIES = {
  // URGENT_NEEDS
  EMERGENCY_HEALING: 8,
  EMERGENCY_EATING: 8,

  // PEACEFUL  
  FOLLOWING: 9,
  MINING: 6,
  BUILDING: 6,
  FARMING: 6,
  SLEEPING: 6,
  SHELTERING: 6,
  IDLE: 1,

  // COMBAT
  COMBAT: 7,
  FLEEING: 7,
  MELEE_ATTACKING: 7,
  RANGED_ATTACKING: 7,
  DEFENDING: 7,

  // TASKS
  DEPOSIT_ITEMS: 6.5,
  REPAIR_ARMOR_TOOLS: 5,
}
